"""Endpoint registry — 351 endpoints (143 TWSE OpenAPI + 1 TWSE web API + 207 TPEX OpenAPI)."""

from __future__ import annotations

from dataclasses import dataclass, field


TPEX_BASE_URL = "https://www.tpex.org.tw/openapi/v1"


@dataclass(frozen=True, slots=True)
class EndpointDef:
    """Definition of a single TWSE endpoint.

    For standard OpenAPI endpoints, only path/cli_name/group/description are needed.
    For web API endpoints (e.g. T86), set base_url to override the default base,
    default_params for required query parameters, and field_aliases to map
    verbose Chinese field names to short English names.
    """

    path: str
    cli_name: str
    group: str
    description: str
    code_field: str | None = None
    fields: list[str] = field(default_factory=list)
    base_url: str | None = None
    default_params: dict[str, str] = field(default_factory=dict)
    field_aliases: dict[str, str] = field(default_factory=dict)


ENDPOINTS: dict[str, EndpointDef] = {
    "company.punish": EndpointDef(
        path="/announcement/punish",
        cli_name="punish",
        group="company",
        description="集中市場公布處置股票",
    ),
    "company.applylistingforeign": EndpointDef(
        path="/company/applylistingForeign",
        cli_name="applylistingforeign",
        group="company",
        description="外國公司向證交所申請第一上市之公司",
    ),
    "company.applylistinglocal": EndpointDef(
        path="/company/applylistingLocal",
        cli_name="applylistinglocal",
        group="company",
        description="申請上市之本國公司",
    ),
    "company.newlisting": EndpointDef(
        path="/company/newlisting",
        cli_name="newlisting",
        group="company",
        description="最近上市公司",
    ),
    "company.suspendlistingcsvandhtml": EndpointDef(
        path="/company/suspendListingCsvAndHtml",
        cli_name="suspendlistingcsvandhtml",
        group="company",
        description="終止上市公司",
    ),
    "company.t187ap02-l": EndpointDef(
        path="/opendata/t187ap02_L",
        cli_name="t187ap02-l",
        group="company",
        description="上市公司持股逾 10% 大股東名單",
        code_field="公司代號",
    ),
    "company.t187ap03-l": EndpointDef(
        path="/opendata/t187ap03_L",
        cli_name="t187ap03-l",
        group="company",
        description="上市公司基本資料",
        code_field="公司代號",
        fields=["出表日期", "公司代號", "公司名稱", "公司簡稱", "產業別", "住址", "董事長", "總經理", "成立日期", "上市日期", "實收資本額"],
    ),
    "company.t187ap03-p": EndpointDef(
        path="/opendata/t187ap03_P",
        cli_name="t187ap03-p",
        group="company",
        description="公開發行公司基本資料",
        code_field="公司代號",
    ),
    "company.t187ap04-l": EndpointDef(
        path="/opendata/t187ap04_L",
        cli_name="t187ap04-l",
        group="company",
        description="上市公司每日重大訊息",
        code_field="公司代號",
    ),
    "company.t187ap05-p": EndpointDef(
        path="/opendata/t187ap05_P",
        cli_name="t187ap05-p",
        group="company",
        description="公開發行公司每月營業收入彙總表",
        code_field="公司代號",
    ),
    "company.t187ap08-l": EndpointDef(
        path="/opendata/t187ap08_L",
        cli_name="t187ap08-l",
        group="company",
        description="上市公司董事、監察人持股不足法定成數彙總表",
        code_field="公司代號",
    ),
    "company.t187ap09-l": EndpointDef(
        path="/opendata/t187ap09_L",
        cli_name="t187ap09-l",
        group="company",
        description="上市公司董事、監察人質權設定占董事及監察人實際持有股數彙總表",
        code_field="公司代號",
    ),
    "company.t187ap10-l": EndpointDef(
        path="/opendata/t187ap10_L",
        cli_name="t187ap10-l",
        group="company",
        description="上市公司董事、監察人持股不足法定成數連續達3個月以上彙總表",
        code_field="公司代號",
    ),
    "company.t187ap11-l": EndpointDef(
        path="/opendata/t187ap11_L",
        cli_name="t187ap11-l",
        group="company",
        description="上市公司董監事持股餘額明細資料",
        code_field="公司代號",
    ),
    "company.t187ap12-l": EndpointDef(
        path="/opendata/t187ap12_L",
        cli_name="t187ap12-l",
        group="company",
        description="上市公司每日內部人持股轉讓事前申報表-持股轉讓日報表",
        code_field="公司代號",
    ),
    "company.t187ap13-l": EndpointDef(
        path="/opendata/t187ap13_L",
        cli_name="t187ap13-l",
        group="company",
        description="上市公司每日內部人持股轉讓事前申報表-持股未轉讓日報表",
        code_field="公司代號",
    ),
    "company.t187ap14-l": EndpointDef(
        path="/opendata/t187ap14_L",
        cli_name="t187ap14-l",
        group="company",
        description="上市公司各產業EPS統計資訊",
        code_field="公司代號",
    ),
    "company.t187ap22-l": EndpointDef(
        path="/opendata/t187ap22_L",
        cli_name="t187ap22-l",
        group="company",
        description="上市公司金管會證券期貨局裁罰案件專區",
        code_field="公司代號",
    ),
    "company.t187ap23-l": EndpointDef(
        path="/opendata/t187ap23_L",
        cli_name="t187ap23-l",
        group="company",
        description="上市公司違反資訊申報、重大訊息及說明記者會規定專區",
        code_field="公司代號",
    ),
    "company.t187ap24-l": EndpointDef(
        path="/opendata/t187ap24_L",
        cli_name="t187ap24-l",
        group="company",
        description="上市公司經營權及營業範圍異(變)動專區-經營權異動公司",
        code_field="公司代號",
    ),
    "company.t187ap25-l": EndpointDef(
        path="/opendata/t187ap25_L",
        cli_name="t187ap25-l",
        group="company",
        description="上市公司經營權及營業範圍異(變)動專區-營業範圍重大變更公司",
        code_field="公司代號",
    ),
    "company.t187ap26-l": EndpointDef(
        path="/opendata/t187ap26_L",
        cli_name="t187ap26-l",
        group="company",
        description="上市公司經營權及營業範圍異(變)動專區-經營權異動且營業範圍重大變更停止買賣公司",
        code_field="公司代號",
    ),
    "company.t187ap27-l": EndpointDef(
        path="/opendata/t187ap27_L",
        cli_name="t187ap27-l",
        group="company",
        description="上市公司經營權及營業範圍異(變)動專區-經營權異動且營業範圍重大變更列為變更交易公司",
        code_field="公司代號",
    ),
    "company.t187ap29-a-l": EndpointDef(
        path="/opendata/t187ap29_A_L",
        cli_name="t187ap29-a-l",
        group="company",
        description="上市公司董事酬金相關資訊 ",
        code_field="公司代號",
    ),
    "company.t187ap29-b-l": EndpointDef(
        path="/opendata/t187ap29_B_L",
        cli_name="t187ap29-b-l",
        group="company",
        description="上市公司監察人酬金相關資訊 ",
        code_field="公司代號",
    ),
    "company.t187ap29-c-l": EndpointDef(
        path="/opendata/t187ap29_C_L",
        cli_name="t187ap29-c-l",
        group="company",
        description="上市公司合併報表董事酬金相關資訊 ",
        code_field="公司代號",
    ),
    "company.t187ap29-d-l": EndpointDef(
        path="/opendata/t187ap29_D_L",
        cli_name="t187ap29-d-l",
        group="company",
        description="上市公司合併報表監察人酬金相關資訊 ",
        code_field="公司代號",
    ),
    "company.t187ap30-l": EndpointDef(
        path="/opendata/t187ap30_L",
        cli_name="t187ap30-l",
        group="company",
        description="上市公司獨立董監事兼任情形彙總表",
        code_field="公司代號",
    ),
    "company.t187ap32-l": EndpointDef(
        path="/opendata/t187ap32_L",
        cli_name="t187ap32-l",
        group="company",
        description="上市公司公司治理之相關規程規則",
        code_field="公司代號",
    ),
    "company.t187ap33-l": EndpointDef(
        path="/opendata/t187ap33_L",
        cli_name="t187ap33-l",
        group="company",
        description="上市公司董事長是否兼任總經理",
        code_field="公司代號",
    ),
    "company.t187ap34-l": EndpointDef(
        path="/opendata/t187ap34_L",
        cli_name="t187ap34-l",
        group="company",
        description="上市公司採累積投票制、全額連記法、候選人提名制選任董監事及當選資料彙總表",
        code_field="公司代號",
    ),
    "company.t187ap35-l": EndpointDef(
        path="/opendata/t187ap35_L",
        cli_name="t187ap35-l",
        group="company",
        description="上市公司股東行使提案權情形彙總表",
        code_field="公司代號",
    ),
    "company.t187ap38-l": EndpointDef(
        path="/opendata/t187ap38_L",
        cli_name="t187ap38-l",
        group="company",
        description="上市公司股東會公告-召集股東常(臨時)會公告資料彙總表(95年度起適用)",
        code_field="公司代號",
    ),
    "company.t187ap41-l": EndpointDef(
        path="/opendata/t187ap41_L",
        cli_name="t187ap41-l",
        group="company",
        description="上市公司召開股東常 (臨時) 會日期、地點及採用電子投票情形等資料彙總表",
        code_field="公司代號",
    ),
    "company.t187ap45-l": EndpointDef(
        path="/opendata/t187ap45_L",
        cli_name="t187ap45-l",
        group="company",
        description="上市公司股利分派情形",
        code_field="公司代號",
        fields=["出表日期", "公司代號", "公司名稱", "股利年度", "股東配發-盈餘分配之現金股利(元/股)", "股東配發-盈餘轉增資配股(元/股)"],
    ),
    "company.t187ap46-l-1": EndpointDef(
        path="/opendata/t187ap46_L_1",
        cli_name="t187ap46-l-1",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-溫室氣體排放",
        code_field="公司代號",
    ),
    "company.t187ap46-l-10": EndpointDef(
        path="/opendata/t187ap46_L_10",
        cli_name="t187ap46-l-10",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-燃料管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-11": EndpointDef(
        path="/opendata/t187ap46_L_11",
        cli_name="t187ap46-l-11",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-產品生命週期",
        code_field="公司代號",
    ),
    "company.t187ap46-l-12": EndpointDef(
        path="/opendata/t187ap46_L_12",
        cli_name="t187ap46-l-12",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-食品安全",
        code_field="公司代號",
    ),
    "company.t187ap46-l-13": EndpointDef(
        path="/opendata/t187ap46_L_13",
        cli_name="t187ap46-l-13",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-供應鏈管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-14": EndpointDef(
        path="/opendata/t187ap46_L_14",
        cli_name="t187ap46-l-14",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-產品品質與安全",
        code_field="公司代號",
    ),
    "company.t187ap46-l-15": EndpointDef(
        path="/opendata/t187ap46_L_15",
        cli_name="t187ap46-l-15",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-社區關係",
        code_field="公司代號",
    ),
    "company.t187ap46-l-16": EndpointDef(
        path="/opendata/t187ap46_L_16",
        cli_name="t187ap46-l-16",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-資訊安全",
        code_field="公司代號",
    ),
    "company.t187ap46-l-17": EndpointDef(
        path="/opendata/t187ap46_L_17",
        cli_name="t187ap46-l-17",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-普惠金融",
        code_field="公司代號",
    ),
    "company.t187ap46-l-18": EndpointDef(
        path="/opendata/t187ap46_L_18",
        cli_name="t187ap46-l-18",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-持股及控制力",
        code_field="公司代號",
    ),
    "company.t187ap46-l-19": EndpointDef(
        path="/opendata/t187ap46_L_19",
        cli_name="t187ap46-l-19",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-風險管理政策",
        code_field="公司代號",
    ),
    "company.t187ap46-l-2": EndpointDef(
        path="/opendata/t187ap46_L_2",
        cli_name="t187ap46-l-2",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-能源管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-20": EndpointDef(
        path="/opendata/t187ap46_L_20",
        cli_name="t187ap46-l-20",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-反競爭行為法律訴訟",
        code_field="公司代號",
    ),
    "company.t187ap46-l-21": EndpointDef(
        path="/opendata/t187ap46_L_21",
        cli_name="t187ap46-l-21",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-職業安全衛生",
        code_field="公司代號",
    ),
    "company.t187ap46-l-3": EndpointDef(
        path="/opendata/t187ap46_L_3",
        cli_name="t187ap46-l-3",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-水資源管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-4": EndpointDef(
        path="/opendata/t187ap46_L_4",
        cli_name="t187ap46-l-4",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-廢棄物管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-5": EndpointDef(
        path="/opendata/t187ap46_L_5",
        cli_name="t187ap46-l-5",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-人力發展",
        code_field="公司代號",
    ),
    "company.t187ap46-l-6": EndpointDef(
        path="/opendata/t187ap46_L_6",
        cli_name="t187ap46-l-6",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-董事會",
        code_field="公司代號",
    ),
    "company.t187ap46-l-7": EndpointDef(
        path="/opendata/t187ap46_L_7",
        cli_name="t187ap46-l-7",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-投資人溝通",
        code_field="公司代號",
    ),
    "company.t187ap46-l-8": EndpointDef(
        path="/opendata/t187ap46_L_8",
        cli_name="t187ap46-l-8",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-氣候相關議題管理",
        code_field="公司代號",
    ),
    "company.t187ap46-l-9": EndpointDef(
        path="/opendata/t187ap46_L_9",
        cli_name="t187ap46-l-9",
        group="company",
        description="上市公司企業ESG資訊揭露彙總資料-功能性委員會",
        code_field="公司代號",
    ),
    "other.bfi61u": EndpointDef(
        path="/exchangeReport/BFI61U",
        cli_name="bfi61u",
        group="other",
        description="中央登錄公債補息資料表",
        code_field="Code",
    ),
    "other.eventlist": EndpointDef(
        path="/news/eventList",
        cli_name="eventlist",
        group="other",
        description="證交所活動訊息",
    ),
    "other.newslist": EndpointDef(
        path="/news/newsList",
        cli_name="newslist",
        group="other",
        description="證交所新聞",
    ),
    "other.t187ap47-l": EndpointDef(
        path="/opendata/t187ap47_L",
        cli_name="t187ap47-l",
        group="other",
        description="基金基本資料彙總表",
        code_field="公司代號",
    ),
    "broker.etfrank": EndpointDef(
        path="/ETFReport/ETFRank",
        cli_name="etfrank",
        group="broker",
        description="定期定額交易戶數統計排行月報表",
    ),
    "broker.brokerlist": EndpointDef(
        path="/brokerService/brokerList",
        cli_name="brokerlist",
        group="broker",
        description="證券商總公司基本資料",
        code_field="Code",
        fields=["Code", "Name", "EstablishmentDate", "Address", "Telephone"],
    ),
    "broker.secregdata": EndpointDef(
        path="/brokerService/secRegData",
        cli_name="secregdata",
        group="broker",
        description="開辦定期定額業務證券商名單",
        code_field="Code",
    ),
    "broker.opendata-brk01": EndpointDef(
        path="/opendata/OpenData_BRK01",
        cli_name="opendata-brk01",
        group="broker",
        description="證券商營業員男女人數統計資料",
        code_field="公司代號",
    ),
    "broker.opendata-brk02": EndpointDef(
        path="/opendata/OpenData_BRK02",
        cli_name="opendata-brk02",
        group="broker",
        description="證券商分公司基本資料",
        code_field="公司代號",
    ),
    "broker.t187ap01": EndpointDef(
        path="/opendata/t187ap01",
        cli_name="t187ap01",
        group="broker",
        description="券商業務別人員數",
        code_field="公司代號",
    ),
    "broker.t187ap18": EndpointDef(
        path="/opendata/t187ap18",
        cli_name="t187ap18",
        group="broker",
        description="證券商基本資料",
        code_field="公司代號",
    ),
    "broker.t187ap20": EndpointDef(
        path="/opendata/t187ap20",
        cli_name="t187ap20",
        group="broker",
        description="各券商每月月計表",
        code_field="公司代號",
    ),
    "broker.t187ap21": EndpointDef(
        path="/opendata/t187ap21",
        cli_name="t187ap21",
        group="broker",
        description="各券商收支概況表資料",
        code_field="公司代號",
    ),
    "stock.mi-index4": EndpointDef(
        path="/exchangeReport/MI_INDEX4",
        cli_name="mi-index4",
        group="stock",
        description="每日上市上櫃跨市場成交資訊",
        code_field="Code",
    ),
    "stock.frmsa": EndpointDef(
        path="/indicesReport/FRMSA",
        cli_name="frmsa",
        group="stock",
        description="寶島股價指數歷史資料",
    ),
    "stock.mfi94u": EndpointDef(
        path="/indicesReport/MFI94U",
        cli_name="mfi94u",
        group="stock",
        description="發行量加權股價報酬指數",
    ),
    "stock.mi-5mins-hist": EndpointDef(
        path="/indicesReport/MI_5MINS_HIST",
        cli_name="mi-5mins-hist",
        group="stock",
        description="發行量加權股價指數歷史資料",
    ),
    "stock.tai50i": EndpointDef(
        path="/indicesReport/TAI50I",
        cli_name="tai50i",
        group="stock",
        description="臺灣 50 指數歷史資料",
    ),
    "stock.t187ap36-l": EndpointDef(
        path="/opendata/t187ap36_L",
        cli_name="t187ap36-l",
        group="stock",
        description="上市認購(售)權證年度發行量概況統計表",
        code_field="公司代號",
    ),
    "stock.t187ap42-l": EndpointDef(
        path="/opendata/t187ap42_L",
        cli_name="t187ap42-l",
        group="stock",
        description="上市認購(售)權證每日成交資料檔",
        code_field="公司代號",
    ),
    "stock.t187ap43-l": EndpointDef(
        path="/opendata/t187ap43_L",
        cli_name="t187ap43-l",
        group="stock",
        description="上市認購(售)權證交易人數檔",
        code_field="公司代號",
    ),
    "stock.bfzfzu-t": EndpointDef(
        path="/Announcement/BFZFZU_T",
        cli_name="bfzfzu-t",
        group="stock",
        description="投資理財節目異常推介個股",
    ),
    "stock.twt96u": EndpointDef(
        path="/SBL/TWT96U",
        cli_name="twt96u",
        group="stock",
        description="上市上櫃股票當日可借券賣出股數",
    ),
    "stock.notetrans": EndpointDef(
        path="/announcement/notetrans",
        cli_name="notetrans",
        group="stock",
        description="集中市場公布注意累計次數異常資訊",
    ),
    "stock.notice": EndpointDef(
        path="/announcement/notice",
        cli_name="notice",
        group="stock",
        description="集中市場當日公布注意股票",
    ),
    "stock.bfiauu-d": EndpointDef(
        path="/block/BFIAUU_d",
        cli_name="bfiauu-d",
        group="stock",
        description="集中市場鉅額交易日成交量值統計",
    ),
    "stock.bfiauu-m": EndpointDef(
        path="/block/BFIAUU_m",
        cli_name="bfiauu-m",
        group="stock",
        description="集中市場鉅額交易月成交量值統計",
    ),
    "stock.bfiauu-y": EndpointDef(
        path="/block/BFIAUU_y",
        cli_name="bfiauu-y",
        group="stock",
        description="集中市場鉅額交易年成交量值統計",
    ),
    "stock.bfi84u": EndpointDef(
        path="/exchangeReport/BFI84U",
        cli_name="bfi84u",
        group="stock",
        description="集中市場停資停券預告表",
        code_field="Code",
    ),
    "stock.bft41u": EndpointDef(
        path="/exchangeReport/BFT41U",
        cli_name="bft41u",
        group="stock",
        description="集中市場盤後定價交易",
        code_field="Code",
    ),
    "stock.bwibbu-all": EndpointDef(
        path="/exchangeReport/BWIBBU_ALL",
        cli_name="bwibbu-all",
        group="stock",
        description="上市個股日本益比、殖利率及股價淨值比（依代碼查詢）",
        code_field="Code",
        fields=["Code", "Name", "PEratio", "DividendYield", "PBratio"],
    ),
    "stock.bwibbu-d": EndpointDef(
        path="/exchangeReport/BWIBBU_d",
        cli_name="bwibbu-d",
        group="stock",
        description="上市個股日本益比、殖利率及股價淨值比（依日期查詢）",
        code_field="Code",
    ),
    "stock.fmnptk-all": EndpointDef(
        path="/exchangeReport/FMNPTK_ALL",
        cli_name="fmnptk-all",
        group="stock",
        description="上市個股年成交資訊",
        code_field="Code",
    ),
    "stock.fmsrfk-all": EndpointDef(
        path="/exchangeReport/FMSRFK_ALL",
        cli_name="fmsrfk-all",
        group="stock",
        description="上市個股月成交資訊",
        code_field="Code",
    ),
    "stock.fmtqik": EndpointDef(
        path="/exchangeReport/FMTQIK",
        cli_name="fmtqik",
        group="stock",
        description="集中市場每日市場成交資訊",
        code_field="Code",
    ),
    "stock.mi-5mins": EndpointDef(
        path="/exchangeReport/MI_5MINS",
        cli_name="mi-5mins",
        group="stock",
        description="每 5 秒委託成交統計",
        code_field="Code",
    ),
    "stock.mi-index": EndpointDef(
        path="/exchangeReport/MI_INDEX",
        cli_name="mi-index",
        group="stock",
        description="每日收盤行情-大盤統計資訊",
        code_field="Code",
        fields=["日期", "指數", "收盤指數", "漲跌", "漲跌點數", "漲跌百分比", "特殊處理註記"],
    ),
    "stock.mi-index20": EndpointDef(
        path="/exchangeReport/MI_INDEX20",
        cli_name="mi-index20",
        group="stock",
        description="集中市場每日成交量前二十名證券",
        code_field="Code",
    ),
    "stock.mi-margn": EndpointDef(
        path="/exchangeReport/MI_MARGN",
        cli_name="mi-margn",
        group="stock",
        description="集中市場融資融券餘額",
        code_field="Code",
    ),
    "stock.stock-day-all": EndpointDef(
        path="/exchangeReport/STOCK_DAY_ALL",
        cli_name="stock-day-all",
        group="stock",
        description="上市個股日成交資訊",
        code_field="Code",
        fields=["Code", "Name", "TradeVolume", "TradeValue", "OpeningPrice", "HighestPrice", "LowestPrice", "ClosingPrice", "Change", "Transaction"],
    ),
    "stock.stock-day-avg-all": EndpointDef(
        path="/exchangeReport/STOCK_DAY_AVG_ALL",
        cli_name="stock-day-avg-all",
        group="stock",
        description="上市個股日收盤價及月平均價",
        code_field="Code",
        fields=["Code", "Name", "ClosingPrice", "MonthlyAveragePrice"],
    ),
    "stock.stock-first": EndpointDef(
        path="/exchangeReport/STOCK_FIRST",
        cli_name="stock-first",
        group="stock",
        description="每日第一上市外國股票成交量值",
        code_field="Code",
    ),
    "stock.twt48u-all": EndpointDef(
        path="/exchangeReport/TWT48U_ALL",
        cli_name="twt48u-all",
        group="stock",
        description="上市股票除權除息預告表",
        code_field="Code",
    ),
    "stock.twt53u": EndpointDef(
        path="/exchangeReport/TWT53U",
        cli_name="twt53u",
        group="stock",
        description="集中市場零股交易行情單",
        code_field="Code",
    ),
    "stock.twt84u": EndpointDef(
        path="/exchangeReport/TWT84U",
        cli_name="twt84u",
        group="stock",
        description="上市個股股價升降幅度",
        code_field="Code",
    ),
    "stock.twt85u": EndpointDef(
        path="/exchangeReport/TWT85U",
        cli_name="twt85u",
        group="stock",
        description="集中市場證券變更交易",
        code_field="Code",
    ),
    "stock.twt88u": EndpointDef(
        path="/exchangeReport/TWT88U",
        cli_name="twt88u",
        group="stock",
        description="上市個股首五日無漲跌幅",
        code_field="Code",
    ),
    "stock.twtawu": EndpointDef(
        path="/exchangeReport/TWTAWU",
        cli_name="twtawu",
        group="stock",
        description="集中市場暫停交易證券",
        code_field="Code",
    ),
    "stock.twtb4u": EndpointDef(
        path="/exchangeReport/TWTB4U",
        cli_name="twtb4u",
        group="stock",
        description="上市股票每日當日沖銷交易標的及統計",
        code_field="Code",
    ),
    "stock.twtbau1": EndpointDef(
        path="/exchangeReport/TWTBAU1",
        cli_name="twtbau1",
        group="stock",
        description="集中市場暫停先賣後買當日沖銷交易標的預告表",
        code_field="Code",
    ),
    "stock.twtbau2": EndpointDef(
        path="/exchangeReport/TWTBAU2",
        cli_name="twtbau2",
        group="stock",
        description="集中市場暫停先賣後買當日沖銷交易歷史查詢",
        code_field="Code",
    ),
    "stock.mi-qfiis-cat": EndpointDef(
        path="/fund/MI_QFIIS_cat",
        cli_name="mi-qfiis-cat",
        group="stock",
        description="集中市場外資及陸資投資類股持股比率表",
    ),
    "stock.mi-qfiis-sort-20": EndpointDef(
        path="/fund/MI_QFIIS_sort_20",
        cli_name="mi-qfiis-sort-20",
        group="stock",
        description="集中市場外資及陸資持股前 20 名彙總表",
    ),
    "stock.holidayschedule": EndpointDef(
        path="/holidaySchedule/holidaySchedule",
        cli_name="holidayschedule",
        group="stock",
        description="有價證券集中交易市場開（休）市日期",
    ),
    "stock.t187ap19": EndpointDef(
        path="/opendata/t187ap19",
        cli_name="t187ap19",
        group="stock",
        description="電子式交易統計資訊",
        code_field="公司代號",
    ),
    "stock.t187ap37-l": EndpointDef(
        path="/opendata/t187ap37_L",
        cli_name="t187ap37-l",
        group="stock",
        description="上市權證基本資料彙總表",
        code_field="公司代號",
    ),
    "stock.twtazu-od": EndpointDef(
        path="/opendata/twtazu_od",
        cli_name="twtazu-od",
        group="stock",
        description="集中市場漲跌證券數統計表",
        code_field="公司代號",
    ),
    "company.t187ap05-l": EndpointDef(
        path="/opendata/t187ap05_L",
        cli_name="t187ap05-l",
        group="company",
        description="上市公司每月營業收入彙總表",
        code_field="公司代號",
        fields=["出表日期", "資料年月", "公司代號", "公司名稱", "產業別", "營業收入-當月營收", "營業收入-去年當月營收", "營業收入-去年同月增減(%)"],
    ),
    "company.t187ap06-l-basi": EndpointDef(
        path="/opendata/t187ap06_L_basi",
        cli_name="t187ap06-l-basi",
        group="company",
        description="上市公司綜合損益表(金融業)",
        code_field="公司代號",
    ),
    "company.t187ap06-l-bd": EndpointDef(
        path="/opendata/t187ap06_L_bd",
        cli_name="t187ap06-l-bd",
        group="company",
        description="上市公司綜合損益表(證券期貨業)",
        code_field="公司代號",
    ),
    "company.t187ap06-l-ci": EndpointDef(
        path="/opendata/t187ap06_L_ci",
        cli_name="t187ap06-l-ci",
        group="company",
        description="上市公司綜合損益表(一般業)",
        code_field="公司代號",
    ),
    "company.t187ap06-l-fh": EndpointDef(
        path="/opendata/t187ap06_L_fh",
        cli_name="t187ap06-l-fh",
        group="company",
        description="上市公司綜合損益表(金控業)",
        code_field="公司代號",
    ),
    "company.t187ap06-l-ins": EndpointDef(
        path="/opendata/t187ap06_L_ins",
        cli_name="t187ap06-l-ins",
        group="company",
        description="上市公司綜合損益表(保險業)",
        code_field="公司代號",
    ),
    "company.t187ap06-l-mim": EndpointDef(
        path="/opendata/t187ap06_L_mim",
        cli_name="t187ap06-l-mim",
        group="company",
        description="上市公司綜合損益表(異業)",
        code_field="公司代號",
    ),
    "company.t187ap06-x-basi": EndpointDef(
        path="/opendata/t187ap06_X_basi",
        cli_name="t187ap06-x-basi",
        group="company",
        description="公發公司綜合損益表-金融業",
        code_field="公司代號",
    ),
    "company.t187ap06-x-bd": EndpointDef(
        path="/opendata/t187ap06_X_bd",
        cli_name="t187ap06-x-bd",
        group="company",
        description="公發公司綜合損益表-證券期貨業",
        code_field="公司代號",
    ),
    "company.t187ap06-x-ci": EndpointDef(
        path="/opendata/t187ap06_X_ci",
        cli_name="t187ap06-x-ci",
        group="company",
        description="公發公司綜合損益表-一般業",
        code_field="公司代號",
    ),
    "company.t187ap06-x-fh": EndpointDef(
        path="/opendata/t187ap06_X_fh",
        cli_name="t187ap06-x-fh",
        group="company",
        description="公發公司綜合損益表-金控業",
        code_field="公司代號",
    ),
    "company.t187ap06-x-ins": EndpointDef(
        path="/opendata/t187ap06_X_ins",
        cli_name="t187ap06-x-ins",
        group="company",
        description="公發公司綜合損益表-保險業",
        code_field="公司代號",
    ),
    "company.t187ap06-x-mim": EndpointDef(
        path="/opendata/t187ap06_X_mim",
        cli_name="t187ap06-x-mim",
        group="company",
        description="公發公司綜合損益表-異業",
        code_field="公司代號",
    ),
    "company.t187ap07-l-basi": EndpointDef(
        path="/opendata/t187ap07_L_basi",
        cli_name="t187ap07-l-basi",
        group="company",
        description="上市公司資產負債表(金融業)",
        code_field="公司代號",
    ),
    "company.t187ap07-l-bd": EndpointDef(
        path="/opendata/t187ap07_L_bd",
        cli_name="t187ap07-l-bd",
        group="company",
        description="上市公司資產負債表(證券期貨業)",
        code_field="公司代號",
    ),
    "company.t187ap07-l-ci": EndpointDef(
        path="/opendata/t187ap07_L_ci",
        cli_name="t187ap07-l-ci",
        group="company",
        description="上市公司資產負債表(一般業)",
        code_field="公司代號",
    ),
    "company.t187ap07-l-fh": EndpointDef(
        path="/opendata/t187ap07_L_fh",
        cli_name="t187ap07-l-fh",
        group="company",
        description="上市公司資產負債表(金控業)",
        code_field="公司代號",
    ),
    "company.t187ap07-l-ins": EndpointDef(
        path="/opendata/t187ap07_L_ins",
        cli_name="t187ap07-l-ins",
        group="company",
        description="上市公司資產負債表(保險業)",
        code_field="公司代號",
    ),
    "company.t187ap07-l-mim": EndpointDef(
        path="/opendata/t187ap07_L_mim",
        cli_name="t187ap07-l-mim",
        group="company",
        description="上市公司資產負債表(異業)",
        code_field="公司代號",
    ),
    "company.t187ap07-x-basi": EndpointDef(
        path="/opendata/t187ap07_X_basi",
        cli_name="t187ap07-x-basi",
        group="company",
        description="公發公司資產負債表-金融業",
        code_field="公司代號",
    ),
    "company.t187ap07-x-bd": EndpointDef(
        path="/opendata/t187ap07_X_bd",
        cli_name="t187ap07-x-bd",
        group="company",
        description="公發公司資產負債表-證券期貨業",
        code_field="公司代號",
    ),
    "company.t187ap07-x-ci": EndpointDef(
        path="/opendata/t187ap07_X_ci",
        cli_name="t187ap07-x-ci",
        group="company",
        description="公發公司資產負債表-一般業",
        code_field="公司代號",
    ),
    "company.t187ap07-x-fh": EndpointDef(
        path="/opendata/t187ap07_X_fh",
        cli_name="t187ap07-x-fh",
        group="company",
        description="公發公司資產負債表-金控業",
        code_field="公司代號",
    ),
    "company.t187ap07-x-ins": EndpointDef(
        path="/opendata/t187ap07_X_ins",
        cli_name="t187ap07-x-ins",
        group="company",
        description="公發公司資產負債表-保險業",
        code_field="公司代號",
    ),
    "company.t187ap07-x-mim": EndpointDef(
        path="/opendata/t187ap07_X_mim",
        cli_name="t187ap07-x-mim",
        group="company",
        description="公發公司資產負債表-異業",
        code_field="公司代號",
    ),
    "company.t187ap11-p": EndpointDef(
        path="/opendata/t187ap11_P",
        cli_name="t187ap11-p",
        group="company",
        description="公發公司董監事持股餘額明細",
        code_field="公司代號",
    ),
    "company.t187ap15-l": EndpointDef(
        path="/opendata/t187ap15_L",
        cli_name="t187ap15-l",
        group="company",
        description="上市公司截至各季綜合損益財測達成情形(簡式)",
        code_field="公司代號",
    ),
    "company.t187ap16-l": EndpointDef(
        path="/opendata/t187ap16_L",
        cli_name="t187ap16-l",
        group="company",
        description="上市公司當季綜合損益經會計師查核(核閱)數與當季預測數差異達百分之十以上者，或截至當季累計差異達百分之二十以上者(簡式)",
        code_field="公司代號",
    ),
    "company.t187ap17-l": EndpointDef(
        path="/opendata/t187ap17_L",
        cli_name="t187ap17-l",
        group="company",
        description="上市公司營益分析查詢彙總表(全體公司彙總報表)",
        code_field="公司代號",
    ),
    "company.t187ap31-l": EndpointDef(
        path="/opendata/t187ap31_L",
        cli_name="t187ap31-l",
        group="company",
        description="上市公司財務報告經監察人承認情形",
        code_field="公司代號",
    ),
    "stock.t86": EndpointDef(
        path="/fund/T86",
        cli_name="t86",
        group="stock",
        description="三大法人買賣超日報",
        code_field="Code",
        fields=["Code", "Name", "ForeignNet", "TrustNet", "DealerNet", "InstitutionalNet"],
        base_url="https://www.twse.com.tw/rwd/zh",
        default_params={"selectType": "ALLBUT0999", "response": "json"},
        field_aliases={
            "證券代號": "Code",
            "證券名稱": "Name",
            "外陸資買進股數(不含外資自營商)": "ForeignBuy",
            "外陸資賣出股數(不含外資自營商)": "ForeignSell",
            "外陸資買賣超股數(不含外資自營商)": "ForeignNet",
            "外資自營商買進股數": "ForeignDealerBuy",
            "外資自營商賣出股數": "ForeignDealerSell",
            "外資自營商買賣超股數": "ForeignDealerNet",
            "投信買進股數": "TrustBuy",
            "投信賣出股數": "TrustSell",
            "投信買賣超股數": "TrustNet",
            "自營商買賣超股數": "DealerNet",
            "自營商買進股數(自行買賣)": "DealerPropBuy",
            "自營商賣出股數(自行買賣)": "DealerPropSell",
            "自營商買賣超股數(自行買賣)": "DealerPropNet",
            "自營商買進股數(避險)": "DealerHedgeBuy",
            "自營商賣出股數(避險)": "DealerHedgeSell",
            "自營商買賣超股數(避險)": "DealerHedgeNet",
            "三大法人買賣超股數": "InstitutionalNet",
        },
    ),
    # ── TPEX (OTC) stock trading endpoints ───────────────────────────────
    "otc.mainboard-daily-close-quotes": EndpointDef(
        path="/tpex_mainboard_daily_close_quotes",
        cli_name="mainboard-daily-close-quotes",
        group="otc",
        description="上櫃個股日成交資訊",
        code_field="SecuritiesCompanyCode",
        fields=["SecuritiesCompanyCode", "CompanyName", "Close", "Change", "Open", "High", "Low", "Average", "TradingShares", "TransactionAmount", "TransactionNumber"],
        base_url=TPEX_BASE_URL,
    ),
    "otc.mainboard-quotes": EndpointDef(
        path="/tpex_mainboard_quotes",
        cli_name="mainboard-quotes",
        group="otc",
        description="上櫃股票收盤行情",
        code_field="SecuritiesCompanyCode",
        fields=["SecuritiesCompanyCode", "CompanyName", "Close", "Change", "Open", "High", "Low", "TradingShares", "TransactionAmount", "TransactionNumber"],
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-daily-trading": EndpointDef(
        path="/tpex_3insti_daily_trading",
        cli_name="3insti-daily-trading",
        group="otc",
        description="上櫃三大法人買賣超日報",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-summary": EndpointDef(
        path="/tpex_3insti_summary",
        cli_name="3insti-summary",
        group="otc",
        description="上櫃三大法人買賣金額統計表",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-qfii-trading": EndpointDef(
        path="/tpex_3insti_qfii_trading",
        cli_name="3insti-qfii-trading",
        group="otc",
        description="上櫃外資及陸資買賣超彙總表",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-qfii": EndpointDef(
        path="/tpex_3insti_qfii",
        cli_name="3insti-qfii",
        group="otc",
        description="上櫃外資及陸資持股排名",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-qfii-industry": EndpointDef(
        path="/tpex_3insti_qfii_industry",
        cli_name="3insti-qfii-industry",
        group="otc",
        description="上櫃外資及陸資持股比率按產業別統計表",
        base_url=TPEX_BASE_URL,
    ),
    "otc.mainboard-margin-balance": EndpointDef(
        path="/tpex_mainboard_margin_balance",
        cli_name="mainboard-margin-balance",
        group="otc",
        description="上櫃融資融券餘額",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.mainboard-peratio-analysis": EndpointDef(
        path="/tpex_mainboard_peratio_analysis",
        cli_name="mainboard-peratio-analysis",
        group="otc",
        description="上櫃個股日本益比、殖利率及股價淨值比",
        code_field="SecuritiesCompanyCode",
        fields=["SecuritiesCompanyCode", "CompanyName", "PriceEarningRatio", "DividendPerShare", "YieldRatio", "PriceBookRatio"],
        base_url=TPEX_BASE_URL,
    ),
    "otc.exright-prepost": EndpointDef(
        path="/tpex_exright_prepost",
        cli_name="exright-prepost",
        group="otc",
        description="上櫃除權除息預告表",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.exright-daily": EndpointDef(
        path="/tpex_exright_daily",
        cli_name="exright-daily",
        group="otc",
        description="上櫃除權除息每日結果",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.index": EndpointDef(
        path="/tpex_index",
        cli_name="index",
        group="otc",
        description="櫃買指數歷史資料",
        base_url=TPEX_BASE_URL,
    ),
    "otc.intraday-trading-statistics": EndpointDef(
        path="/tpex_intraday_trading_statistics",
        cli_name="intraday-trading-statistics",
        group="otc",
        description="上櫃當日沖銷交易統計資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.odd-stock": EndpointDef(
        path="/tpex_odd_stock",
        cli_name="odd-stock",
        group="otc",
        description="上櫃零股交易行情",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.off-market": EndpointDef(
        path="/tpex_off_market",
        cli_name="off-market",
        group="otc",
        description="上櫃盤後定價交易",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc.mainboard-highlight": EndpointDef(
        path="/tpex_mainborad_highlight",
        cli_name="mainboard-highlight",
        group="otc",
        description="上櫃市場概況",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-trading-index": EndpointDef(
        path="/tpex_daily_trading_index",
        cli_name="daily-trading-index",
        group="otc",
        description="上櫃每日市場成交資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.esb-latest-statistics": EndpointDef(
        path="/tpex_esb_latest_statistics",
        cli_name="esb-latest-statistics",
        group="otc",
        description="興櫃股票行情",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) company/financial endpoints ───────────────────────────
    "otc_company.t187ap03-o": EndpointDef(
        path="/mopsfin_t187ap03_O",
        cli_name="t187ap03-o",
        group="otc_company",
        description="上櫃公司基本資料",
        code_field="SecuritiesCompanyCode",
        fields=["Date", "SecuritiesCompanyCode", "CompanyName", "CompanyAbbreviation", "Registration", "SecuritiesIndustryCode", "Address"],
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap05-o": EndpointDef(
        path="/mopsfin_t187ap05_O",
        cli_name="t187ap05-o",
        group="otc_company",
        description="上櫃公司每月營業收入彙總表",
        code_field="公司代號",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap06-o-ci": EndpointDef(
        path="/mopsfin_t187ap06_O_ci",
        cli_name="t187ap06-o-ci",
        group="otc_company",
        description="上櫃公司綜合損益表(一般業)",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap07-o-ci": EndpointDef(
        path="/mopsfin_t187ap07_O_ci",
        cli_name="t187ap07-o-ci",
        group="otc_company",
        description="上櫃公司資產負債表(一般業)",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap11-o": EndpointDef(
        path="/mopsfin_t187ap11_O",
        cli_name="t187ap11-o",
        group="otc_company",
        description="上櫃公司董監事持股餘額明細資料",
        code_field="公司代號",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap14-o": EndpointDef(
        path="/mopsfin_t187ap14_O",
        cli_name="t187ap14-o",
        group="otc_company",
        description="上櫃公司各產業EPS統計資訊",
        code_field="SecuritiesCompanyCode",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap39-o": EndpointDef(
        path="/mopsfin_t187ap39_O",
        cli_name="t187ap39-o",
        group="otc_company",
        description="上櫃公司股利分派情形",
        code_field="公司代號",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) stock trading — Phase 2 ────────────────────────
    "otc.securities": EndpointDef(
        path="/tpex_securities",
        cli_name="securities",
        group="otc",
        description="上櫃股票現股當沖交易標的資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.spendi-today": EndpointDef(
        path="/tpex_spendi_today",
        cli_name="spendi-today",
        group="otc",
        description="上櫃當日公布暫停/恢復交易股票",
        base_url=TPEX_BASE_URL,
    ),
    "otc.spendi-history": EndpointDef(
        path="/tpex_spendi_history",
        cli_name="spendi-history",
        group="otc",
        description="上櫃歷史公布暫停/恢復交易股票",
        base_url=TPEX_BASE_URL,
    ),
    "otc.active-broker-volume": EndpointDef(
        path="/tpex_active_broker_volume",
        cli_name="active-broker-volume",
        group="otc",
        description="上櫃成交量值排行-券商進出排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-sbl": EndpointDef(
        path="/tpex_margin_sbl",
        cli_name="margin-sbl",
        group="otc",
        description="上櫃融資融券暨借券餘額",
        base_url=TPEX_BASE_URL,
    ),
    "otc.cmode": EndpointDef(
        path="/tpex_cmode",
        cli_name="cmode",
        group="otc",
        description="上櫃變更交易方式、股票分割",
        base_url=TPEX_BASE_URL,
    ),
    "otc.esb-applicant-companies": EndpointDef(
        path="/tpex_esb_applicant_companies",
        cli_name="esb-applicant-companies",
        group="otc",
        description="上櫃申請登錄興櫃公司",
        base_url=TPEX_BASE_URL,
    ),
    "otc.trading-warning-information": EndpointDef(
        path="/tpex_trading_warning_information",
        cli_name="trading-warning-information",
        group="otc",
        description="上櫃公布注意交易資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.disposal-information": EndpointDef(
        path="/tpex_disposal_information",
        cli_name="disposal-information",
        group="otc",
        description="上櫃公布處置資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.trading-warning-note": EndpointDef(
        path="/tpex_trading_warning_note",
        cli_name="trading-warning-note",
        group="otc",
        description="上櫃注意交易資訊累計資料",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-term": EndpointDef(
        path="/tpex_margin_trading_term",
        cli_name="margin-trading-term",
        group="otc",
        description="上櫃信用交易停止公告",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-adjust": EndpointDef(
        path="/tpex_margin_trading_adjust",
        cli_name="margin-trading-adjust",
        group="otc",
        description="上櫃信用交易調整公告",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-lend": EndpointDef(
        path="/tpex_margin_trading_lend",
        cli_name="margin-trading-lend",
        group="otc",
        description="上櫃信用交易融券賣出利率",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-marginspot": EndpointDef(
        path="/tpex_margin_trading_marginspot",
        cli_name="margin-trading-marginspot",
        group="otc",
        description="上櫃信用交易融資融券餘額",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-margin-mark": EndpointDef(
        path="/tpex_margin_trading_margin_mark",
        cli_name="margin-trading-margin-mark",
        group="otc",
        description="上櫃信用交易融資融券標的",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-margin-used": EndpointDef(
        path="/tpex_margin_trading_margin_used",
        cli_name="margin-trading-margin-used",
        group="otc",
        description="上櫃信用交易融資使用率",
        base_url=TPEX_BASE_URL,
    ),
    "otc.margin-trading-short-sell": EndpointDef(
        path="/tpex_margin_trading_short_sell",
        cli_name="margin-trading-short-sell",
        group="otc",
        description="上櫃信用交易借券賣出排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-dealer-trading": EndpointDef(
        path="/tpex_3insti_dealer_trading",
        cli_name="3insti-dealer-trading",
        group="otc",
        description="上櫃自營商買賣超彙總表",
        base_url=TPEX_BASE_URL,
    ),
    "otc.ceil-non-trading": EndpointDef(
        path="/tpex_ceil_non_trading",
        cli_name="ceil-non-trading",
        group="otc",
        description="上櫃漲跌停未成交買賣資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc.short-sell": EndpointDef(
        path="/tpex_short_sell",
        cli_name="short-sell",
        group="otc",
        description="上櫃借券賣出成交值及餘額",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-broker1": EndpointDef(
        path="/tpex_daily_broker1",
        cli_name="daily-broker1",
        group="otc",
        description="上櫃每日券商營收統計",
        base_url=TPEX_BASE_URL,
    ),
    "otc.active-dollar-volume": EndpointDef(
        path="/tpex_active_dollar_volume",
        cli_name="active-dollar-volume",
        group="otc",
        description="上櫃個股成交金額排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.active-advanced": EndpointDef(
        path="/tpex_active_advanced",
        cli_name="active-advanced",
        group="otc",
        description="上櫃個股漲幅排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.active-declined": EndpointDef(
        path="/tpex_active_declined",
        cli_name="active-declined",
        group="otc",
        description="上櫃個股跌幅排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.intraday-fee": EndpointDef(
        path="/tpex_intraday_fee",
        cli_name="intraday-fee",
        group="otc",
        description="上櫃當沖借券費率",
        base_url=TPEX_BASE_URL,
    ),
    "otc.intraday-trading-pre": EndpointDef(
        path="/tpex_intraday_trading_pre",
        cli_name="intraday-trading-pre",
        group="otc",
        description="上櫃當沖交易預告停止公告",
        base_url=TPEX_BASE_URL,
    ),
    "otc.intraday-trading-his": EndpointDef(
        path="/tpex_intraday_trading_his",
        cli_name="intraday-trading-his",
        group="otc",
        description="上櫃當沖交易歷史資料",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-market-value": EndpointDef(
        path="/tpex_daily_market_value",
        cli_name="daily-market-value",
        group="otc",
        description="上櫃歷史市值排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-turnover": EndpointDef(
        path="/tpex_daily_turnover",
        cli_name="daily-turnover",
        group="otc",
        description="上櫃歷史週轉率排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.trading-volumes-avg": EndpointDef(
        path="/tpex_trading_volumes_avg",
        cli_name="trading-volumes-avg",
        group="otc",
        description="上櫃歷史平均成交量",
        base_url=TPEX_BASE_URL,
    ),
    "otc.trading-amount-avg": EndpointDef(
        path="/tpex_trading_amount_avg",
        cli_name="trading-amount-avg",
        group="otc",
        description="上櫃歷史平均成交金額",
        base_url=TPEX_BASE_URL,
    ),
    "otc.trading-volume-ratio": EndpointDef(
        path="/tpex_trading_volume_ratio",
        cli_name="trading-volume-ratio",
        group="otc",
        description="上櫃歷史成交量值比重",
        base_url=TPEX_BASE_URL,
    ),
    "otc.pe-ratio-top10": EndpointDef(
        path="/tpex_pe_ratio_top10",
        cli_name="pe-ratio-top10",
        group="otc",
        description="上櫃歷史本益比排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-qutoes-block": EndpointDef(
        path="/tpex_daily_qutoes_block",
        cli_name="daily-qutoes-block",
        group="otc",
        description="上櫃鉅額交易每日行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-trading-block": EndpointDef(
        path="/tpex_daily_trading_block",
        cli_name="daily-trading-block",
        group="otc",
        description="上櫃個股鉅額交易每日行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-trading-summary-odd": EndpointDef(
        path="/tpex_daily_trading_summary_odd",
        cli_name="daily-trading-summary-odd",
        group="otc",
        description="上櫃鉅額交易每日彙總",
        base_url=TPEX_BASE_URL,
    ),
    "otc.monthly-trading-summary-block": EndpointDef(
        path="/tpex_monthly_trading_summary_block",
        cli_name="monthly-trading-summary-block",
        group="otc",
        description="上櫃鉅額交易每月彙總",
        base_url=TPEX_BASE_URL,
    ),
    "otc.yearly-trading-summary-block": EndpointDef(
        path="/tpex_yearly_trading_summary_block",
        cli_name="yearly-trading-summary-block",
        group="otc",
        description="上櫃鉅額交易每年彙總",
        base_url=TPEX_BASE_URL,
    ),
    "otc.volume-rank": EndpointDef(
        path="/tpex_volume_rank",
        cli_name="volume-rank",
        group="otc",
        description="上櫃歷史成交量排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.amount-rank": EndpointDef(
        path="/tpex_amount_rank",
        cli_name="amount-rank",
        group="otc",
        description="上櫃歷史成交金額排行",
        base_url=TPEX_BASE_URL,
    ),
    "otc.prvol": EndpointDef(
        path="/tpex_prvol",
        cli_name="prvol",
        group="otc",
        description="上櫃等價成交系統交易分佈",
        base_url=TPEX_BASE_URL,
    ),
    "otc.3insti-trading": EndpointDef(
        path="/tpex_3insti_trading",
        cli_name="3insti-trading",
        group="otc",
        description="上櫃投信買賣超彙總表",
        base_url=TPEX_BASE_URL,
    ),
    "otc.daily-trade-block-day": EndpointDef(
        path="/tpex_daily_trade_block_day",
        cli_name="daily-trade-block-day",
        group="otc",
        description="上櫃鉅額交易歷史資料",
        base_url=TPEX_BASE_URL,
    ),
    "otc.delayed-stock-open": EndpointDef(
        path="/tpex_delayed_stock_open",
        cli_name="delayed-stock-open",
        group="otc",
        description="上櫃每日延後開盤股票",
        base_url=TPEX_BASE_URL,
    ),
    "otc.delayed-stock-close": EndpointDef(
        path="/tpex_delayed_stock_close",
        cli_name="delayed-stock-close",
        group="otc",
        description="上櫃每日延後收盤股票",
        base_url=TPEX_BASE_URL,
    ),
    "otc.ipo-no-limit": EndpointDef(
        path="/tpex_ipo_no_limit",
        cli_name="ipo-no-limit",
        group="otc",
        description="上櫃IPO五日無漲跌幅資訊",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) index series ───────────────────────────────────
    "otc_index.tpex50-index": EndpointDef(
        path="/tpex50_index",
        cli_name="tpex50-index",
        group="otc_index",
        description="富櫃50指數歷史收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex200-change": EndpointDef(
        path="/tpex200_change",
        cli_name="tpex200-change",
        group="otc_index",
        description="富櫃200指數每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpcgi-constituents": EndpointDef(
        path="/tpcgi_constituents",
        cli_name="tpcgi-constituents",
        group="otc_index",
        description="公司治理指數成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpcgi-reward-index": EndpointDef(
        path="/tpcgi_reward_index",
        cli_name="tpcgi-reward-index",
        group="otc_index",
        description="公司治理指數歷史收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpcgi-change": EndpointDef(
        path="/tpcgi_change",
        cli_name="tpcgi-change",
        group="otc_index",
        description="公司治理指數每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex-index-consti": EndpointDef(
        path="/tpex_index_consti",
        cli_name="tpex-index-consti",
        group="otc_index",
        description="指數成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex-reward-index": EndpointDef(
        path="/tpex_reward_index",
        cli_name="tpex-reward-index",
        group="otc_index",
        description="指數及報酬指數收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex50-constituents": EndpointDef(
        path="/tpex50_constituents",
        cli_name="tpex50-constituents",
        group="otc_index",
        description="富櫃50成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex50-change": EndpointDef(
        path="/tpex50_change",
        cli_name="tpex50-change",
        group="otc_index",
        description="富櫃50每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tphd-constituents": EndpointDef(
        path="/tphd_constituents",
        cli_name="tphd-constituents",
        group="otc_index",
        description="高股息指數成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tphd-change": EndpointDef(
        path="/tphd_change",
        cli_name="tphd-change",
        group="otc_index",
        description="高股息指數每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpci-constituents": EndpointDef(
        path="/tpci_constituents",
        cli_name="tpci-constituents",
        group="otc_index",
        description="薪資指數成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpci-change": EndpointDef(
        path="/tpci_change",
        cli_name="tpci-change",
        group="otc_index",
        description="薪資指數每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpci-reward-index": EndpointDef(
        path="/tpci_reward_index",
        cli_name="tpci-reward-index",
        group="otc_index",
        description="薪資指數歷史收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex-emp88-constituents": EndpointDef(
        path="/tpex_emp88_constituents",
        cli_name="tpex-emp88-constituents",
        group="otc_index",
        description="勞就88指數成份股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex-emp88-change": EndpointDef(
        path="/tpex_emp88_change",
        cli_name="tpex-emp88-change",
        group="otc_index",
        description="勞就88指數每日收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex-emp88-reward-index": EndpointDef(
        path="/tpex_emp88_reward_index",
        cli_name="tpex-emp88-reward-index",
        group="otc_index",
        description="勞就88指數歷史收盤",
        base_url=TPEX_BASE_URL,
    ),
    "otc_index.tpex200-constituents": EndpointDef(
        path="/tpex200_constituents",
        cli_name="tpex200-constituents",
        group="otc_index",
        description="富櫃200成份股",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) company/governance ─────────────────────────────
    "otc_company.t187ap41-o": EndpointDef(
        path="/t187ap41_O",
        cli_name="t187ap41-o",
        group="otc_company",
        description="股東常會日期地點",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap05-r": EndpointDef(
        path="/t187ap05_R",
        cli_name="t187ap05-r",
        group="otc_company",
        description="興櫃公司每月營業收入",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap05-oa": EndpointDef(
        path="/mopsfin_t187ap05_OA",
        cli_name="t187ap05-oa",
        group="otc_company",
        description="29類股營收變動",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap05-ob": EndpointDef(
        path="/mopsfin_t187ap05_OB",
        cli_name="t187ap05-ob",
        group="otc_company",
        description="發行公司營收重點",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap35-o": EndpointDef(
        path="/t187ap35_O",
        cli_name="t187ap35-o",
        group="otc_company",
        description="股東提案使用情形",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap37-o": EndpointDef(
        path="/mopsfin_t187ap37_O",
        cli_name="t187ap37-o",
        group="otc_company",
        description="認購(售)權證發行彙總",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap42-o": EndpointDef(
        path="/mopsfin_t187ap42_O",
        cli_name="t187ap42-o",
        group="otc_company",
        description="認購(售)權證每日交易",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap32-o": EndpointDef(
        path="/mopsfin_t187ap32_O",
        cli_name="t187ap32-o",
        group="otc_company",
        description="公司治理相關規章",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap34-o": EndpointDef(
        path="/mopsfin_t187ap34_O",
        cli_name="t187ap34-o",
        group="otc_company",
        description="累積投票、委託書徵求方式",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap33-o": EndpointDef(
        path="/mopsfin_t187ap33_O",
        cli_name="t187ap33-o",
        group="otc_company",
        description="董事長兼任總經理",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap31-o": EndpointDef(
        path="/mopsfin_t187ap31_O",
        cli_name="t187ap31-o",
        group="otc_company",
        description="財務報告會計師認可",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap09-o": EndpointDef(
        path="/mopsfin_t187ap09_O",
        cli_name="t187ap09-o",
        group="otc_company",
        description="董監事學經歷",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap10-o": EndpointDef(
        path="/mopsfin_t187ap10_O",
        cli_name="t187ap10-o",
        group="otc_company",
        description="董監事持股不足",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap24-o": EndpointDef(
        path="/mopsfin_t187ap24_O",
        cli_name="t187ap24-o",
        group="otc_company",
        description="營業範圍變更",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap25-o": EndpointDef(
        path="/mopsfin_t187ap25_O",
        cli_name="t187ap25-o",
        group="otc_company",
        description="重大營業變更",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap36-o": EndpointDef(
        path="/mopsfin_t187ap36_O",
        cli_name="t187ap36-o",
        group="otc_company",
        description="認購(售)權證年度發行",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap03-r": EndpointDef(
        path="/mopsfin_t187ap03_R",
        cli_name="t187ap03-r",
        group="otc_company",
        description="興櫃公司基本資料",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap04-o": EndpointDef(
        path="/mopsfin_t187ap04_O",
        cli_name="t187ap04-o",
        group="otc_company",
        description="每日重大訊息公告",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap01": EndpointDef(
        path="/mopsfin_t187ap01",
        cli_name="t187ap01",
        group="otc_company",
        description="券商從業人員按部門統計",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap02-o": EndpointDef(
        path="/mopsfin_t187ap02_O",
        cli_name="t187ap02-o",
        group="otc_company",
        description="持股超過10%大股東",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap26-o": EndpointDef(
        path="/mopsfin_t187ap26_O",
        cli_name="t187ap26-o",
        group="otc_company",
        description="營業範圍變更/下櫃",
        base_url=TPEX_BASE_URL,
    ),
    "otc_company.t187ap27-o": EndpointDef(
        path="/mopsfin_t187ap27_O",
        cli_name="t187ap27-o",
        group="otc_company",
        description="營業變更為買賣業",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) ESG disclosures ────────────────────────────────
    "otc_esg.t187ap46-o-21": EndpointDef(
        path="/t187ap46_O_21",
        cli_name="t187ap46-o-21",
        group="otc_esg",
        description="ESG：職業安全衛生",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-9": EndpointDef(
        path="/t187ap46_O_9",
        cli_name="t187ap46-o-9",
        group="otc_esg",
        description="ESG：功能性委員會",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-8": EndpointDef(
        path="/t187ap46_O_8",
        cli_name="t187ap46-o-8",
        group="otc_esg",
        description="ESG：氣候治理",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-20": EndpointDef(
        path="/t187ap46_O_20",
        cli_name="t187ap46-o-20",
        group="otc_esg",
        description="ESG：反競爭法訴訟",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-19": EndpointDef(
        path="/t187ap46_O_19",
        cli_name="t187ap46-o-19",
        group="otc_esg",
        description="ESG：風險管理政策",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-15": EndpointDef(
        path="/t187ap46_O_15",
        cli_name="t187ap46-o-15",
        group="otc_esg",
        description="ESG：社區關係",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-13": EndpointDef(
        path="/t187ap46_O_13",
        cli_name="t187ap46-o-13",
        group="otc_esg",
        description="ESG：供應鏈管理",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-12": EndpointDef(
        path="/t187ap46_O_12",
        cli_name="t187ap46-o-12",
        group="otc_esg",
        description="ESG：食品安全",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-14": EndpointDef(
        path="/t187ap46_O_14",
        cli_name="t187ap46-o-14",
        group="otc_esg",
        description="ESG：產品品質安全",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-4": EndpointDef(
        path="/t187ap46_O_4",
        cli_name="t187ap46-o-4",
        group="otc_esg",
        description="ESG：廢棄物管理",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-2": EndpointDef(
        path="/t187ap46_O_2",
        cli_name="t187ap46-o-2",
        group="otc_esg",
        description="ESG：能源管理",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-7": EndpointDef(
        path="/t187ap46_O_7",
        cli_name="t187ap46-o-7",
        group="otc_esg",
        description="ESG：投資人溝通",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-1": EndpointDef(
        path="/t187ap46_O_1",
        cli_name="t187ap46-o-1",
        group="otc_esg",
        description="ESG：溫室氣體排放",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-6": EndpointDef(
        path="/t187ap46_O_6",
        cli_name="t187ap46-o-6",
        group="otc_esg",
        description="ESG：董事會",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-5": EndpointDef(
        path="/t187ap46_O_5",
        cli_name="t187ap46-o-5",
        group="otc_esg",
        description="ESG：人力資源發展",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esg.t187ap46-o-3": EndpointDef(
        path="/t187ap46_O_3",
        cli_name="t187ap46-o-3",
        group="otc_esg",
        description="ESG：水資源管理",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) financial statements ───────────────────────────
    "otc_financial.t187ap07-o-basi": EndpointDef(
        path="/mopsfin_t187ap07_O_basi",
        cli_name="t187ap07-o-basi",
        group="otc_financial",
        description="資產負債表(金融業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-o-bd": EndpointDef(
        path="/mopsfin_t187ap07_O_bd",
        cli_name="t187ap07-o-bd",
        group="otc_financial",
        description="資產負債表(證券業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-o-fh": EndpointDef(
        path="/mopsfin_t187ap07_O_fh",
        cli_name="t187ap07-o-fh",
        group="otc_financial",
        description="資產負債表(金控業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-o-ins": EndpointDef(
        path="/mopsfin_t187ap07_O_ins",
        cli_name="t187ap07-o-ins",
        group="otc_financial",
        description="資產負債表(保險業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-o-mim": EndpointDef(
        path="/mopsfin_t187ap07_O_mim",
        cli_name="t187ap07-o-mim",
        group="otc_financial",
        description="資產負債表(綜合業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-basi": EndpointDef(
        path="/mopsfin_t187ap06_O_basi",
        cli_name="t187ap06-o-basi",
        group="otc_financial",
        description="綜合損益表(金融業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-bd": EndpointDef(
        path="/mopsfin_t187ap06_O_bd",
        cli_name="t187ap06-o-bd",
        group="otc_financial",
        description="綜合損益表(證券業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-fh": EndpointDef(
        path="/mopsfin_t187ap06_O_fh",
        cli_name="t187ap06-o-fh",
        group="otc_financial",
        description="綜合損益表(金控業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-ins": EndpointDef(
        path="/mopsfin_t187ap06_O_ins",
        cli_name="t187ap06-o-ins",
        group="otc_financial",
        description="綜合損益表(保險業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-mim": EndpointDef(
        path="/mopsfin_t187ap06_O_mim",
        cli_name="t187ap06-o-mim",
        group="otc_financial",
        description="綜合損益表(綜合業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-basia": EndpointDef(
        path="/mopsfin_t187ap06_O_basiA",
        cli_name="t187ap06-o-basia",
        group="otc_financial",
        description="財務資訊(金融業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-bda": EndpointDef(
        path="/mopsfin_t187ap06_O_bdA",
        cli_name="t187ap06-o-bda",
        group="otc_financial",
        description="財務資訊(證券業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-cia": EndpointDef(
        path="/mopsfin_t187ap06_O_ciA",
        cli_name="t187ap06-o-cia",
        group="otc_financial",
        description="財務資訊(一般業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-fha": EndpointDef(
        path="/mopsfin_t187ap06_O_fhA",
        cli_name="t187ap06-o-fha",
        group="otc_financial",
        description="財務資訊(金控業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-insa": EndpointDef(
        path="/mopsfin_t187ap06_O_insA",
        cli_name="t187ap06-o-insa",
        group="otc_financial",
        description="財務資訊(保險業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-o-mima": EndpointDef(
        path="/mopsfin_t187ap06_O_mimA",
        cli_name="t187ap06-o-mima",
        group="otc_financial",
        description="財務資訊(綜合業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-bd": EndpointDef(
        path="/mopsfin_t187ap07_U_bd",
        cli_name="t187ap07-u-bd",
        group="otc_financial",
        description="資產負債表(興櫃-證券業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-ci": EndpointDef(
        path="/mopsfin_t187ap07_U_ci",
        cli_name="t187ap07-u-ci",
        group="otc_financial",
        description="資產負債表(興櫃-一般業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-fh": EndpointDef(
        path="/mopsfin_t187ap07_U_fh",
        cli_name="t187ap07-u-fh",
        group="otc_financial",
        description="資產負債表(興櫃-金控業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-ins": EndpointDef(
        path="/mopsfin_t187ap07_U_ins",
        cli_name="t187ap07-u-ins",
        group="otc_financial",
        description="資產負債表(興櫃-保險業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-mim": EndpointDef(
        path="/mopsfin_t187ap07_U_mim",
        cli_name="t187ap07-u-mim",
        group="otc_financial",
        description="資產負債表(興櫃-綜合業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-basi": EndpointDef(
        path="/mopsfin_t187ap06_U_basi",
        cli_name="t187ap06-u-basi",
        group="otc_financial",
        description="綜合損益表(興櫃-金融業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-bd": EndpointDef(
        path="/mopsfin_t187ap06_U_bd",
        cli_name="t187ap06-u-bd",
        group="otc_financial",
        description="綜合損益表(興櫃-證券業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-ci": EndpointDef(
        path="/mopsfin_t187ap06_U_ci",
        cli_name="t187ap06-u-ci",
        group="otc_financial",
        description="綜合損益表(興櫃-一般業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-fh": EndpointDef(
        path="/mopsfin_t187ap06_U_fh",
        cli_name="t187ap06-u-fh",
        group="otc_financial",
        description="綜合損益表(興櫃-金控業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-ins": EndpointDef(
        path="/mopsfin_t187ap06_U_ins",
        cli_name="t187ap06-u-ins",
        group="otc_financial",
        description="綜合損益表(興櫃-保險業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap06-u-mim": EndpointDef(
        path="/mopsfin_t187ap06_U_mim",
        cli_name="t187ap06-u-mim",
        group="otc_financial",
        description="綜合損益表(興櫃-綜合業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap07-u-basi": EndpointDef(
        path="/mopsfin_t187ap07_U_basi",
        cli_name="t187ap07-u-basi",
        group="otc_financial",
        description="資產負債表(興櫃-金融業)",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap11-r": EndpointDef(
        path="/mopsfin_t187ap11_R",
        cli_name="t187ap11-r",
        group="otc_financial",
        description="興櫃董監事持股餘額明細",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap15-o": EndpointDef(
        path="/mopsfin_t187ap15_O",
        cli_name="t187ap15-o",
        group="otc_financial",
        description="季累計營收預估",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.t187ap16-o": EndpointDef(
        path="/mopsfin_t187ap16_O",
        cli_name="t187ap16-o",
        group="otc_financial",
        description="季營收偏離統計",
        base_url=TPEX_BASE_URL,
    ),
    "otc_financial.187ap17-o": EndpointDef(
        path="/mopsfin_187ap17_O",
        cli_name="187ap17-o",
        group="otc_financial",
        description="獲利分析查詢彙總",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) emerging stock board ───────────────────────────
    "otc_esb.disposal-information": EndpointDef(
        path="/tpex_esb_disposal_information",
        cli_name="disposal-information",
        group="otc_esb",
        description="興櫃處置資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esb.warning-information": EndpointDef(
        path="/tpex_esb_warning_information",
        cli_name="warning-information",
        group="otc_esb",
        description="興櫃注意交易資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esb.recommended-dealer": EndpointDef(
        path="/tpex_esb_recommended_dealer",
        cli_name="recommended-dealer",
        group="otc_esb",
        description="興櫃推薦證券商及股票",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esb.eps-rank": EndpointDef(
        path="/tpex_esb_eps_rank",
        cli_name="eps-rank",
        group="otc_esb",
        description="興櫃公司EPS排名",
        base_url=TPEX_BASE_URL,
    ),
    "otc_esb.capitals-rank": EndpointDef(
        path="/tpex_esb_capitals_rank",
        cli_name="capitals-rank",
        group="otc_esb",
        description="興櫃公司實收資本額排名",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) GISA (創櫃) ──────────────────────────────────────
    "otc_gisa.highlight": EndpointDef(
        path="/tpex_gisa_highlight",
        cli_name="highlight",
        group="otc_gisa",
        description="創櫃市場概況",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gisa.company": EndpointDef(
        path="/tpex_gisa_company",
        cli_name="company",
        group="otc_gisa",
        description="創櫃公司資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gisa.financing-before": EndpointDef(
        path="/tpex_gisa_financing_before",
        cli_name="financing-before",
        group="otc_gisa",
        description="創櫃登錄前募資",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gisa.financing-history": EndpointDef(
        path="/tpex_gisa_financing_history",
        cli_name="financing-history",
        group="otc_gisa",
        description="創櫃募資系統紀錄",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gisa.financing-in-process": EndpointDef(
        path="/tpex_gisa_financing_in_process",
        cli_name="financing-in-process",
        group="otc_gisa",
        description="創櫃處理中募資資訊",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) warrants ───────────────────────────────────────
    "otc_warrant.warrant-gold": EndpointDef(
        path="/tpex_warrant_gold",
        cli_name="warrant-gold",
        group="otc_warrant",
        description="黃金現貨權證發行資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-gold-quts": EndpointDef(
        path="/tpex_warrant_gold_quts",
        cli_name="warrant-gold-quts",
        group="otc_warrant",
        description="黃金現貨權證收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-daily-quts": EndpointDef(
        path="/tpex_warrant_daily_quts",
        cli_name="warrant-daily-quts",
        group="otc_warrant",
        description="權證每日收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-monthly-quts": EndpointDef(
        path="/tpex_warrant_monthly_quts",
        cli_name="warrant-monthly-quts",
        group="otc_warrant",
        description="權證每月收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-issue": EndpointDef(
        path="/tpex_warrant_issue",
        cli_name="warrant-issue",
        group="otc_warrant",
        description="權證發行資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wcb-daily-quts": EndpointDef(
        path="/tpex_warrant_wcb_daily_quts",
        cli_name="warrant-wcb-daily-quts",
        group="otc_warrant",
        description="牛熊證每日收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wcb-monthly-quts": EndpointDef(
        path="/tpex_warrant_wcb_monthly_quts",
        cli_name="warrant-wcb-monthly-quts",
        group="otc_warrant",
        description="牛熊證每月收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wcb-issue": EndpointDef(
        path="/tpex_warrant_wcb_issue",
        cli_name="warrant-wcb-issue",
        group="otc_warrant",
        description="牛熊證發行資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wxy-daily-quts": EndpointDef(
        path="/tpex_warrant_wxy_daily_quts",
        cli_name="warrant-wxy-daily-quts",
        group="otc_warrant",
        description="展延型牛熊證每日收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wxy-monthly-quts": EndpointDef(
        path="/tpex_warrant_wxy_monthly_quts",
        cli_name="warrant-wxy-monthly-quts",
        group="otc_warrant",
        description="展延型牛熊證每月收盤行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-wxy-issue": EndpointDef(
        path="/tpex_warrant_wxy_issue",
        cli_name="warrant-wxy-issue",
        group="otc_warrant",
        description="展延型牛熊證發行資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-quts": EndpointDef(
        path="/tpex_warrant_quts",
        cli_name="warrant-quts",
        group="otc_warrant",
        description="個別權證成交資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-statistics": EndpointDef(
        path="/tpex_warrant_statistics",
        cli_name="warrant-statistics",
        group="otc_warrant",
        description="權證每日交易參與人統計",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant": EndpointDef(
        path="/tpex_warrant",
        cli_name="warrant",
        group="otc_warrant",
        description="股票權證資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-suspend-today": EndpointDef(
        path="/tpex_warrant_suspend_today",
        cli_name="warrant-suspend-today",
        group="otc_warrant",
        description="權證當日暫停/恢復交易",
        base_url=TPEX_BASE_URL,
    ),
    "otc_warrant.warrant-suspend-history": EndpointDef(
        path="/tpex_warrant_suspend_history",
        cli_name="warrant-suspend-history",
        group="otc_warrant",
        description="權證歷史暫停/恢復交易",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) open-ended funds ───────────────────────────────
    "otc_fund.latest": EndpointDef(
        path="/tpex_opfund_latest",
        cli_name="latest",
        group="otc_fund",
        description="開放式基金每日行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_fund.recommended-dealer": EndpointDef(
        path="/tpex_opfund_recommended_dealer",
        cli_name="recommended-dealer",
        group="otc_fund",
        description="開放式基金推薦證券商及基金",
        base_url=TPEX_BASE_URL,
    ),
    "otc_fund.market-highlight": EndpointDef(
        path="/tpex_opfund_market_highlight",
        cli_name="market-highlight",
        group="otc_fund",
        description="開放式基金市場概況",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) gold spot ──────────────────────────────────────
    "otc_gold.market-highlight": EndpointDef(
        path="/tpex_gold_market_highlight",
        cli_name="market-highlight",
        group="otc_gold",
        description="黃金現貨市場概況",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gold.recommended-dealer": EndpointDef(
        path="/tpex_gold_recommended_dealer",
        cli_name="recommended-dealer",
        group="otc_gold",
        description="黃金現貨交易商及產品",
        base_url=TPEX_BASE_URL,
    ),
    "otc_gold.latest": EndpointDef(
        path="/tpex_gold_latest",
        cli_name="latest",
        group="otc_gold",
        description="黃金現貨每日行情",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) bonds ──────────────────────────────────────────
    "otc_bond.tpex-dpsp-monthly-cbmcs007": EndpointDef(
        path="/tpex_dpsp_monthly_CBmcs007",
        cli_name="tpex-dpsp-monthly-cbmcs007",
        group="otc_bond",
        description="可轉換公司債ASO/ASW銀行承銷",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.tpex-international-bond-quotes": EndpointDef(
        path="/tpex_international_bond_quotes",
        cli_name="tpex-international-bond-quotes",
        group="otc_bond",
        description="國際債券盤中行情",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.tpex-international-bond-trade": EndpointDef(
        path="/tpex_international_bond_trade",
        cli_name="tpex-international-bond-trade",
        group="otc_bond",
        description="國際債券盤中成交",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.tpex-international-bond-issue-investor": EndpointDef(
        path="/tpex_international_bond_issue_investor",
        cli_name="tpex-international-bond-issue-investor",
        group="otc_bond",
        description="國際債券一般投資人適用",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.tpex-international-bond-issue-org": EndpointDef(
        path="/tpex_international_bond_issue_org",
        cli_name="tpex-international-bond-issue-org",
        group="otc_bond",
        description="國際債券專業投資人適用",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.bddos216utf": EndpointDef(
        path="/BDdos216UTF",
        cli_name="bddos216utf",
        group="otc_bond",
        description="美金計價固定利率非可贖回債券定價",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.bddos215utf": EndpointDef(
        path="/BDdos215UTF",
        cli_name="bddos215utf",
        group="otc_bond",
        description="美金計價附息可贖回債券定價",
        base_url=TPEX_BASE_URL,
    ),
    "otc_bond.bddos209utf": EndpointDef(
        path="/BDdos209UTF",
        cli_name="bddos209utf",
        group="otc_bond",
        description="美金計價零息可贖回債券定價",
        base_url=TPEX_BASE_URL,
    ),
    # ── TPEX (OTC) broker/insider data ────────────────────────────
    "otc_broker.t187ap08-o": EndpointDef(
        path="/mopsfin_t187ap08_O",
        cli_name="t187ap08-o",
        group="otc_broker",
        description="董監事持股不足明細",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap12-o": EndpointDef(
        path="/mopsfin_t187ap12_O",
        cli_name="t187ap12-o",
        group="otc_broker",
        description="內部人股票轉讓申報",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap13-o": EndpointDef(
        path="/mopsfin_t187ap13_O",
        cli_name="t187ap13-o",
        group="otc_broker",
        description="內部人未轉讓持股",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap22-o": EndpointDef(
        path="/mopsfin_t187ap22_O",
        cli_name="t187ap22-o",
        group="otc_broker",
        description="金管會證券訴訟案件",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap30-o": EndpointDef(
        path="/mopsfin_t187ap30_O",
        cli_name="t187ap30-o",
        group="otc_broker",
        description="獨立董事兼職",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap29-a-o": EndpointDef(
        path="/mopsfin_t187ap29_A_O",
        cli_name="t187ap29-a-o",
        group="otc_broker",
        description="董事酬金資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.t187ap29-b-o": EndpointDef(
        path="/mopsfin_t187ap29_B_O",
        cli_name="t187ap29-b-o",
        group="otc_broker",
        description="監察人酬金資訊",
        base_url=TPEX_BASE_URL,
    ),
    "otc_broker.bond-cb-daily": EndpointDef(
        path="/bond_cb_daily",
        cli_name="bond-cb-daily",
        group="otc_broker",
        description="可轉債每日券商進出",
        base_url=TPEX_BASE_URL,
    ),
}


def resolve_endpoint(ref: str) -> EndpointDef | None:
    """Resolve dotted name, raw path, or API code to EndpointDef.

    Accepts:
        - Dotted name: "stock.stock-day-all"
        - Raw API path: "/exchangeReport/STOCK_DAY_ALL"
        - API code: "STOCK_DAY_ALL"
    """
    # Direct dotted name match
    if ref in ENDPOINTS:
        return ENDPOINTS[ref]

    # Raw path match
    path = ref if ref.startswith("/") else f"/{ref}"
    for ep in ENDPOINTS.values():
        if ep.path == path:
            return ep

    # API code match (case-insensitive)
    ref_lower = ref.lower().replace("_", "-")
    for key, ep in ENDPOINTS.items():
        if ep.cli_name == ref_lower:
            return ep
        # Also try matching the last segment of the path
        path_code = ep.path.split("/")[-1].lower().replace("_", "-")
        if path_code == ref_lower:
            return ep

    return None


def _has_cjk(text: str) -> bool:
    """Return True if *text* contains any CJK Unified Ideograph."""
    return any("\u4e00" <= ch <= "\u9fff" for ch in text)


def list_endpoints(*, category: str | None = None, search: str | None = None, with_fields: bool = False) -> list[dict]:
    """List endpoints for discovery.

    Args:
        category: Filter by group (stock, company, broker, other).
        search: Search keyword in name, description, or path.
        with_fields: Include field definitions in output.
    """
    results = []
    search_lower = search.lower() if search else None

    for key, ep in sorted(ENDPOINTS.items()):
        if category and ep.group != category:
            continue

        if search_lower:
            searchable = f"{key} {ep.description} {ep.path}".lower()
            if search_lower not in searchable:
                # Fallback: CJK subsequence match (e.g. "營收" matches "營業收入")
                if not _has_cjk(search_lower):
                    continue
                it = iter(searchable)
                if not all(ch in it for ch in search_lower):
                    continue

        entry: dict = {
            "name": key,
            "path": ep.path,
            "group": ep.group,
            "description": ep.description,
        }
        if with_fields and ep.fields:
            entry["fields"] = ep.fields
        results.append(entry)

    return results
